services:
  db:
    image: postgres:16
    # restart: always
    environment:
      POSTGRES_DB: dnd_db
      POSTGRES_USER: dnd_user
      POSTGRES_PASSWORD: dnd_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:8
    # restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn dnd_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
