# Generated by Django 6.0.3 on 2026-03-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_product_rating_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
